# Generated by Django 3.0.4 on 2020-04-17 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20200417_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Customer'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('Ресторан', 'Ресторан'), ('Стрит-фуд', 'Стрит-фуд'), ('Столовая', 'Столовая'), ('Фаст-фуд', 'Фаст-фуд'), ('Кафе', 'Кафе'), ('Паб', 'Паб')], max_length=30, null=True),
        ),
    ]
