# Generated by Django 3.0.4 on 2020-04-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_restaurant_restaurant_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя ресторана'),
        ),
    ]
