# Generated by Django 3.0.4 on 2020-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_auto_20200420_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='adress',
            field=models.CharField(max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(max_length=30, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Моб. номер'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
