# Generated by Django 3.0.4 on 2020-04-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_auto_20200420_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_pic',
            field=models.ImageField(blank=True, default='restaurant_pic', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
