# Generated by Django 3.0.4 on 2020-04-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_auto_20200420_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_pic',
            field=models.ImageField(blank=True, default='restaurant_pic.png', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
