# Generated by Django 3.0.4 on 2020-04-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_auto_20200420_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_pic',
            field=models.ImageField(blank=True, default='form-img.png', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
