# Generated by Django 3.0.4 on 2020-04-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0014_auto_20200420_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_pic',
            field=models.ImageField(blank=True, default='form-img.png', null=True, upload_to='media', verbose_name='Изображение'),
        ),
    ]
