# Generated by Django 3.0.4 on 2020-04-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_auto_20200428_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='form-img.png', null=True, upload_to='media'),
        ),
    ]
