# Generated by Django 3.0.4 on 2020-04-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Горячие блюда', 'Горячие блюда'), ('Холодные блюда', 'Холодные блюда'), ('Закуски', 'Закуски'), ('Десерты', 'Десерты'), ('Напитки', 'Напитки')], max_length=30, null=True),
        ),
    ]
