# Generated by Django 3.0.4 on 2020-04-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0018_menu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Эл.почта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='form-img.png', null=True, upload_to='media', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Горячие блюда', 'Горячие блюда'), ('Холодные блюда', 'Холодные блюда'), ('Закуски', 'Закуски'), ('Десерты', 'Десерты'), ('Напитки', 'Напитки')], max_length=30, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(max_length=300, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weight',
            field=models.FloatField(null=True, verbose_name='Вес'),
        ),
    ]
