# Generated by Django 3.0.4 on 2020-04-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0020_restaurant_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='category',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='description',
        ),
    ]
