# Generated by Django 3.0.4 on 2020-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0021_auto_20200430_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='tags',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_pic',
            field=models.ImageField(blank=True, default='form-img.png', null=True, upload_to='media/menu', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
