# Generated by Django 3.0.4 on 2020-05-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0023_auto_20200502_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenu',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
