# Generated by Django 3.0.4 on 2020-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0024_auto_20200505_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='paypal',
            field=models.CharField(max_length=150, null=True, verbose_name='PayPal'),
        ),
    ]
