# Generated by Django 3.0.4 on 2020-05-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0025_restaurant_paypal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='Адрес'),
        ),
    ]
