# Generated by Django 3.0.4 on 2020-05-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0026_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='raiting',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1),
        ),
    ]
