# Generated by Django 3.0.4 on 2020-05-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0027_restaurant_raiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='raiting',
        ),
    ]
