# Generated by Django 3.0.4 on 2020-05-11 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0028_remove_restaurant_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.CharField(choices=[('Ресторан', 'Ресторан'), ('Закусочная', 'Закусочная'), ('Кафе', 'Кафе'), ('Кофейня', 'Кофейня'), ('Кондитерская', 'Кондитерская'), ('Столовая', 'Столовая')], max_length=30, null=True, verbose_name='Категория'),
        ),
    ]
