# Generated by Django 3.0.4 on 2020-05-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0029_auto_20200511_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_pic',
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
