# Generated by Django 3.0.4 on 2020-05-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0030_auto_20200523_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
